# TP1 : Initiation à Python avec NumPy
Ce notebook reprend les exercices du TP1 et montre les résultats directement dans Google Colab.
Objectifs :
- Manipulation des tableaux avec NumPy
- Indexation et slicing
- Masquage et conditions logiques
- Fonctions mathématiques et statistiques
- Algèbre linéaire avec NumPy

In [ ]:
import numpy as np
import numpy.ma as ma

## 1. Construction d'un tableau

In [ ]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 1.1 Indexation

In [ ]:
print('A[0,0] =', A[0,0])
print('A[0,1] =', A[0,1])

A[0,0] = 1
A[0,1] = 2


### 1.2 Slicing

In [ ]:
print('A[0:2, 1:3] =\n', A[0:2, 1:3])
print('A[:,1] =', A[:,1])
print('A[1,:] =', A[1,:])
print('B = A[:,1:2]\n', A[:,1:2])
print('A[:,-1] =', A[:,-1])
print('A[:,-2] =', A[:,-2])
print('A[:,-2:] =\n', A[:,-2:])

A[0:2, 1:3] =
 [[2 3]
 [5 6]]
A[:,1] = [2 5 8]
A[1,:] = [4 5 6]
B = A[:,1:2]
 [[2]
 [5]
 [8]]
A[:,-1] = [3 6 9]
A[:,-2] = [2 5 8]
A[:,-2:] =
 [[2 3]
 [5 6]
 [8 9]]


### 1.3 Masking

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8])
ma_arr = ma.masked_array(arr, mask=[False,False,False,True,True,True,False,False])
print('Masquage arr =', ma_arr)
print('Somme en ignorant masqués =', ma_arr.sum())

Masquage arr = [1 2 3 -- -- -- 7 8]
Somme en ignorant masqués = 21


### 1.4 Boolean Indexing

In [ ]:
A_bool = A.copy()
A_bool[A_bool < 5] = 10
print('A après condition (A<5)=10:\n', A_bool)

A_bool2 = A.copy()
A_bool2[(A_bool2 < 5) & (A_bool2 > 2)] = 10
print('A après condition 2<A<5=10:\n', A_bool2)

A après condition (A<5)=10:
 [[10 10 10]
 [10  5  6]
 [ 7  8  9]]
A après condition 2<A<5=10:
 [[ 1  2 10]
 [10  5  6]
 [ 7  8  9]]


## 2. Fonctions mathématiques

### 2.1 Fonctions principales

In [ ]:
print('Somme totale =', A.sum())
print('Somme par colonnes =', A.sum(axis=0))
print('Somme par lignes =', A.sum(axis=1))
print('Min global =', A.min(), ' - Max global =', A.max())
print('Indice min global =', A.argmin(), ' - Indice max ligne par ligne =', A.argmax(axis=1))
print('np.sin(A):\n', np.sin(A))
print('np.exp(A):\n', np.exp(A))

Somme totale = 45
Somme par colonnes = [12 15 18]
Somme par lignes = [ 6 15 24]
Min global = 1  - Max global = 9
Indice min global = 0  - Indice max ligne par ligne = [2 2 2]
np.sin(A):
 [[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]
np.exp(A):
 [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


### 2.2 Fonctions statistiques

In [ ]:
print('Moyenne =', A.mean())
print('Ecart-type =', A.std())
print('Variance =', A.var())
print('Matrice de corrélation =\n', np.corrcoef(A))

Moyenne = 5.0
Ecart-type = 2.581988897471611
Variance = 6.666666666666667
Matrice de corrélation =
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### Gestion des NaN

In [ ]:
B = np.random.randn(5,5)
B[0,2]=np.nan
B[4,3]=np.nan
print('Tableau avec NaN:\n', B)
print('Moyenne sans NaN =', np.nanmean(B))
print('Nombre de NaN =', np.isnan(B).sum())
print('Pourcentage de NaN =', np.isnan(B).sum()/B.size)
B[np.isnan(B)] = 0.5
print('Tableau corrigé:\n', B)

Tableau avec NaN:
 [[ 0.10412919  2.4139608          nan  0.95400515 -0.49915263]
 [-1.67302978  1.19588177 -0.03717435 -1.12479523  0.2932445 ]
 [ 0.16248368 -0.78226005 -0.32900815 -0.35475353 -1.66833365]
 [ 0.0686551   0.32869724 -1.36736624 -1.18058942 -0.17835102]
 [-0.69067292 -1.04624957 -1.18273717         nan  1.01674224]]
Moyenne sans NaN = -0.24246408870131098
Nombre de NaN = 2
Pourcentage de NaN = 0.08
Tableau corrigé:
 [[ 0.10412919  2.4139608   0.5         0.95400515 -0.49915263]
 [-1.67302978  1.19588177 -0.03717435 -1.12479523  0.2932445 ]
 [ 0.16248368 -0.78226005 -0.32900815 -0.35475353 -1.66833365]
 [ 0.0686551   0.32869724 -1.36736624 -1.18058942 -0.17835102]
 [-0.69067292 -1.04624957 -1.18273717  0.5         1.01674224]]


### 2.3 Algèbre linéaire

In [ ]:
A2 = np.array([[1,2,3,4]])
B2 = np.array([[1],[2],[3],[4]])
print('A2 =', A2)
print('B2 =\n', B2)
print('Transpose A2 =\n', A2.T)
print('Produit A2.dot(B2) =', A2.dot(B2))

A2 = [[1 2 3 4]]
B2 =
 [[1]
 [2]
 [3]
 [4]]
Transpose A2 =
 [[1]
 [2]
 [3]
 [4]]
Produit A2.dot(B2) = [[30]]


### Broadcasting

In [ ]:
print('A + 2 =\n', A+2)

A + 2 =
 [[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
